---
name: 손지우
surname: 
position: "대학교 학부생"
address: "서울특별시 양천구 목동서로"
phone: 010-9120-****
www: blog.naver.com/bungaedm
email: "bungaedm@naver.com"
twitter: NONE
github: SonJiwoo
linkedin: Jiwoo Son
date: "`r format(Sys.time(), '%B %Y')`"
header-includes:
  - \usepackage{kotex}
output:
  vitae::hyndman:
    pdf_document:
      latex_engine: xelatex
mainfont: NanumBarunpen      
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# 학교

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "문과", "2012~2014", "하나고등학교", "대한민국, 서울",
  "심리학", "2015~", "연세대학교", "대한민국, 서울",
  "응용통계학(이중전공)", "2016~", "연세대학교", "대한민국, 서울"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# 경력

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  "2013 ~ 2013", "심리학 동아리장", "하나고 LIOM Look Into Our Minds 운영",
  "2015 ~ 2015", "심리학 학술모임장", "연세대 심리학 학술소모임 Psy-World 설립 및 운영",
  "2015 ~ 2017", "KSCY 한국청소년학술대회", "인문계열 컨퍼런스 총괄 및 헤드 퍼실리테이터",
  "2016 ~ 현재", "응용통계학과 이중전공", "연세대",
  "2017 ~ 2019", "대한민국 공군", "RAPCON Radar Approach Control",
  "2020 ~ 현재", "ESC", "연세대학교 통계학회 학술부 및 총무"
) %>% 
  brief_entries(
    glue::glue("{Type}"),
    Year, 
    Desc
  )
```

# 수강과목

```{r}
tribble(
  ~Year, ~Type,
  "2015-1", "통계학입문",
  "2016-1", "미분적분학", 
  "2016-1", "통계방법론",
  "2016-2", "선형대수",
  "2016-2", "컴퓨터자료처리",
  "2019-1", "심리통계",
  "2019-1", "데이터사이언스를 위한 확률과정",
  "2019-1", "회귀분석",
  "2019-1", "수리통계학(1)",
  "2019-2", "베이즈통계",
  "2019-2", "수리통계학(2)",
  "2019-2", "시계열분석",
  "2019-2", "금융리스크관리실무와 통계학",
  "2020-1", "범주형자료분석",
  "2020-1", "데이터사이언스입문",
  "2020-1", "데이터마이닝",
  "2020-1", "이론통계학(1)",
  "2020-1", "데이터사이언스(2): 네트워크자료분석"
) %>% 
  brief_entries(
    glue::glue("{Type}"),
    Year
  )
```
